### ISSUE TITLE
Structure the repository

### ISSUE THREAD

**Issue by marta-belles** [dusk-network/trusted-setup#1]
Structure:
1. `README.md`
- Explanation Powers of Tau
- Structure of the repository (folders instructions and contributions)
- How we run the ceremony
- License

2. Folder `instructions`
- `CONTRIBUTE.md` (coordinator, tips for randomness, how to download the software, etc.)
- `VERIFY.md` (instructions to verify the whole ceremony)

4. Folder `contributions`
- Contributions from 88.
- In the `README.md` file of this folder, clarify where the first 1-87 contributions can be found.
- Links to contributions/challenges.

**Comment by marta-belles** [comment]
To write the instructions, see as inspiration:
- https://github.com/dusk-network/powersoftau
- https://github.com/privacy-scaling-explorations/perpetualpowersoftau
- https://ceremony.ethereum.org

**Comment by xevisalle** [comment]
Done and merged.
